### ISSUE TITLE
Unavailable on chrome store

### ISSUE THREAD

**Issue by sanslash332** [lopezloo/yt-live-text2speech#6]
Currently the extension is unavailable from the chrome store, or edge store.
Can you reupload it?

Or if you had problems with google's estrange terms, what appened?

**Comment by lopezloo** [comment]
It was removed from Chrome Web Store because they have changed guidelines. They started requiring all extensions to have icon and screenshot. I will try to add it soon.

**Comment by sanslash332** [comment]
O interesting. thanks for the answer @lopezloo 

Try to use a simple icon and a screenshot of the config panel and you'll be OK :-)

thanks for the add-on, is awesome.
